repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
  - repo: local
    hooks:
      - id: isort-check
        name: isort-check
        entry: uv run isort --check-only --diff
        language: system
        pass_filenames: true
        types: [python]
      - id: black-check
        name: black-check
        entry: uv run black --target-version py311 --check --diff
        language: system
        pass_filenames: true
        types: [python]
      - id: lint
        name: lint
        entry: uv run ruff check
        language: system
        pass_filenames: true
        types: [python]
      # - id: typecheck
      #   name: typecheck
      #   entry: sh -c 'command -v task >/dev/null 2>&1 && task typecheck || go-task typecheck'
      #   language: system
      #   pass_filenames: false
