# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Tell RTD to use uv as the installer
# (works with pyproject.toml + [dependency-groups])
python:
  install:
    - method: uv
      path: .
      extra-dependencies:
        - dev   # install your dev group, which has sphinx + plugins


# Build documentation in the "docs/" directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: docs/source/conf.py


