# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: docs/source/conf.py
