[build-system]
requires = ["setuptools>=80.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = { find = { include = ["gerrytools*"], exclude = ["tests*"] } }

[project]
name = "gerrytools"
version = "2.0.0"
description = "Tools for processing and visualizing districting plans."
readme = "README.md"
authors = [
  { name = "MGGG Redistricting Lab", email = "code@mggg.org" },
]
requires-python = ">=3.11"
license = { text = "MIT" } 

dependencies = [
  # Working with graphs and ensembles
  "networkx>=3.5.0",
  "gerrychain>=0.3.2",
  "jsonlines>=4.0.0",
  "maup>=2.0.3",
  "binary-ensemble>=0.3.0",
  # Data manipulation
  "pandas>=2.3.2",
  "scipy>=1.16.1",
  "numpy>=2.3.2",
  # Geospatial libraries
  "geopandas>=1.1.1",
  "Shapely>=2.0.0",
  # Visualization
  "matplotlib>=3.10.6",
  "seaborn>=0.13.2",
  # Census
  "us>=3.2.0",
  # Misc
  "sortedcontainers",
  "pydantic>=2.11.7",
  # Computer Vision?
  "opencv-python-headless>=4.11.0.86",
  "imageio>=2.37.0",
  # REMOVE!!
  "gurobipy>=12.0.3",
  "pyarrow>=22.0.0",
]

[dependency-groups]
dev = [
  # Linters, formatters, type checkers
  "flake8>=7.3.0",
  "black>=25.1.0",
  "isort>=6.0.1",
  "autopep8>=2.3.2",
  "myst-parser>=4.0.1",
  # Iteractive kernel
  "ipykernel>=6.30.1",
  "ipywidgets>=8.1.7",
  # Testing
  "pytest>=8.4.2",
  "pytest-cov>=6.3.0",
  "pytest-timeout>=2.4.0",
  # Other
  "pre-commit>=4.3.0",
  "ruff>=0.14.9",
]
docs = [
  "myst-parser>=4.0.1",
  "sphinx>=8.2.3",
  "sphinx-copybutton>=0.5.2",
  "sphinx-rtd-theme>=3.0.2",
]
tex = [
    "pymupdf>=1.26.6",
    "pypdfium2>=5.1.0",
    "pyqt6>=6.10.0",
    "pyside6>=6.10.1",
]

[project.optional-dependencies]
mgrp = [
    "docker>=7.1.0",
]

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true

[tool.ruff]
line-length = 100
extend-exclude = [
  "tests",
  "**/__init__.py",
  "gerrychain/vendor"
]

[tool.ruff.lint]
select = ["E", "W", "F"]
ignore = [
    "E501",  # line length handled by black
    "E203",  # whitespace before ':', handled by black
    "E731",  # do not assign lambda expression
    "F541",  # f-string is missing placeholders
]
task-tags = ["TODO", "FIXME", "XXX", "HACK", "NOTE"]

[tool.ruff.lint.pycodestyle]
ignore-overlong-task-comments = true

[tool.pytest.ini_options]
# addopts = "--cov=gerrytools --cov-report=term-missing"
markers = [
  "slow: marks tests as slow (deselect with '-m \"not slow\"')",
  "latex: marks tests that require LaTeX installation",
]
